### ISSUE TITLE
Fan Control Question

### ISSUE THREAD

**Issue by krystofurr** [elar-systems/tb-fan-control#1]
Hello,

 I came across this repository recently looking for a way to control the fan speed on my Tinkerboard.  Luckily I found this and seems to install fine.  Thanks

 I was wondering if you have any further information on how to control the fan speed.  I don't fully understand what I need to configure in the .conf file to lower the speed.  Do I raise the low temp higher ?  Why is the GPIO pin set to 188?  Shouldn't it be 4?  Any basic usage examples would be great!  Thanks again

**Comment by elar-systems** [comment]
Hi,
Good to see that you found my codes useful.
I have to inform you that unfortunately this code has not been designed to control the Fan Speed, rather it designed to turn the fan on and off as per CPU temperature thresholds.
Turns it on, when the CPU temperature reach the max value in conf file, and turns it off, when the CPU gets cool and came bellow the min value which set in the conf file.

Should you need to use fan speed, you still can change the code and alter it to use PWM pins (As the table, physical pin 32 & 33 are hardware base PWM).

PWM is the Pulse Width Modulation that can be used to control dimming of RGB LEDs or to control the direction of a servo motor or in your case Fan Speed.

Regarding Pin number 188, I have used physical pin number 40 and of course 39 for GND (Ground). And as you can see in the GPIO header pin in bellow image, the actual ASUS Pin number you can control through the bus is 188.
You can adjust it as per your need though.

![gpio](https://user-images.githubusercontent.com/14272907/68535857-1da01280-039d-11ea-9c40-d61c1455071b.png)


As a last note, your fan also should be capable to be controlled with various speeds.
Normally 4wire fans are capable(check with your supplier).
The one I had and been using had two wires. Means only On or Off. And that actually was the reason this code initially developed based on the on/off capability rather that fan speed control.

Thanks again,

**Comment by krystofurr** [comment]
I see! Thanks for the response.  I realized now that my fan is a non-pwn type fan ( https://www.amazon.ca/Zebra-Fan-UPGRADE-Raspberry-C4Labs/dp/B01HP4JKLS/ref=sr_1_2?keywords=zebra+fan+upgrade&qid=1573341253&sr=8-2 ).  So I won't have the ability to control it.  Was worth a try.  :D
